name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: pip install uv && uv sync --inexact
    - name: Lint with Ruff
      run: python -m uv run ruff check sqlight
    - name: Run Mypy
      run: python -m uv run mypy sqlight
    - name: Test suite
      run: python -m uv run pytest --cov=sqlight tests
